language: python
python:
    - "3.7"

before_install:
    - sudo apt-get install -y libsm6
    - sudo apt-get install -y libxrender1
    - sudo apt-get install -y libfontconfig1
    - sudo apt-get install -y libice6
    - sudo apt-get install -y ffmpeg
install:
    - pip install -r requirements.txt

addons:
    apt:
        update: true
