os: linux
dist: bionic

language: python
python:
    - "3.8.2"

branches:
    only:
        - master
        - stable
        - dev

addons:
    apt:
        update: true

install:
    - sudo apt install -y libsm6 libxrender1 libfontconfig1 libice6
    - pip install -U pip pipenv
    - pipenv --python 3.8.2
    - pipenv install --dev

before_script:
    - pass

script:
    - pass
#    - pytest
